package com.subsidytracker.common.enums;

public enum ApplicationStatus {
    DRAFT,
    SUBMITTED,
    ELIGIBILITY_PENDING,
    ELIGIBLE,
    NOT_ELIGIBLE,
    MANUAL_REVIEW_REQUIRED,

    FIELD_VERIFICATION_PENDING,
    FIELD_APPROVED,
    FIELD_REJECTED,

    DISTRICT_REVIEW_PENDING,
    DISTRICT_APPROVED,
    DISTRICT_REJECTED,

    FINANCE_REVIEW_PENDING,
    FINANCE_APPROVED,
    FINANCE_REJECTED,

    RE_VERIFICATION_REQUIRED,
    READY_FOR_DISBURSEMENT,
    DISBURSED,
    COMPLETED,
    APPLICATION_CANCELLED
}